// Generated by CodiumAI

'use client';

import * as React from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import { UtensilsCrossed, Package, Receipt } from 'lucide-react';

import {
  SidebarContent,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
} from '@/components/ui/sidebar';

// Simple SVG Logo Placeholder (Fork & Knife)
const RestoFacilLogo = () => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        className="h-6 w-6 shrink-0" // Use Tailwind classes for size
    >
        <path d="M16 2v20"></path>
        <path d="M11 2v11a5 5 0 0 0 10 0V2"></path>
        <path d="M8 2v20"></path>
        <path d="M3 12h3a3 3 0 0 1 0 6H3"></path>
    </svg>
);


export default function AppSidebar() {
  const pathname = usePathname();

  const isActive = (path: string) => pathname === path || pathname.startsWith(path + '/'); // Updated isActive to handle detail pages

  return (
    <>
      <SidebarHeader className="flex items-center gap-2">
         <RestoFacilLogo />
        <h2 className="text-xl font-semibold text-sidebar-foreground group-data-[collapsible=icon]:hidden">
          El Bajón de la Cami {/* Changed from RestoFácil */}
        </h2>
      </SidebarHeader>
      <SidebarContent>
        <SidebarMenu>
          <SidebarMenuItem>
            <Link href="/tables" passHref legacyBehavior>
              <SidebarMenuButton
                isActive={isActive('/tables')}
                tooltip="Mesas" // Changed from Tables
              >
                <UtensilsCrossed />
                <span>Mesas</span> {/* Changed from Tables */}
              </SidebarMenuButton>
            </Link>
          </SidebarMenuItem>
          <SidebarMenuItem>
            <Link href="/inventory" passHref legacyBehavior>
              <SidebarMenuButton
                isActive={isActive('/inventory')}
                tooltip="Inventario" // Changed from Inventory
              >
                <Package />
                <span>Inventario</span> {/* Changed from Inventory */}
              </SidebarMenuButton>
            </Link>
          </SidebarMenuItem>
          <SidebarMenuItem>
            <Link href="/expenses" passHref legacyBehavior>
              <SidebarMenuButton
                isActive={isActive('/expenses')}
                tooltip="Gastos" // Changed from Expenses
              >
                <Receipt />
                <span>Gastos</span> {/* Changed from Expenses */}
              </SidebarMenuButton>
            </Link>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarContent>
    </>
  );
}

